// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replacement.proto

#ifndef PROTOBUF_replacement_2eproto__INCLUDED
#define PROTOBUF_replacement_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace fira_message {
namespace sim_to_ref {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_replacement_2eproto();
void protobuf_AssignDesc_replacement_2eproto();
void protobuf_ShutdownFile_replacement_2eproto();

class BallReplacement;
class Replacement;
class RobotReplacement;

// ===================================================================

class RobotReplacement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.RobotReplacement) */ {
 public:
  RobotReplacement();
  virtual ~RobotReplacement();

  RobotReplacement(const RobotReplacement& from);

  inline RobotReplacement& operator=(const RobotReplacement& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RobotReplacement& default_instance();

  void Swap(RobotReplacement* other);

  // implements Message ----------------------------------------------

  inline RobotReplacement* New() const { return New(NULL); }

  RobotReplacement* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RobotReplacement& from);
  void MergeFrom(const RobotReplacement& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RobotReplacement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fira_message.Robot position = 1;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 1;
  const ::fira_message::Robot& position() const;
  ::fira_message::Robot* mutable_position();
  ::fira_message::Robot* release_position();
  void set_allocated_position(::fira_message::Robot* position);

  // optional bool yellowteam = 5;
  void clear_yellowteam();
  static const int kYellowteamFieldNumber = 5;
  bool yellowteam() const;
  void set_yellowteam(bool value);

  // optional bool turnon = 6;
  void clear_turnon();
  static const int kTurnonFieldNumber = 6;
  bool turnon() const;
  void set_turnon(bool value);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.RobotReplacement)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::fira_message::Robot* position_;
  bool yellowteam_;
  bool turnon_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_replacement_2eproto();
  friend void protobuf_AssignDesc_replacement_2eproto();
  friend void protobuf_ShutdownFile_replacement_2eproto();

  void InitAsDefaultInstance();
  static RobotReplacement* default_instance_;
};
// -------------------------------------------------------------------

class BallReplacement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.BallReplacement) */ {
 public:
  BallReplacement();
  virtual ~BallReplacement();

  BallReplacement(const BallReplacement& from);

  inline BallReplacement& operator=(const BallReplacement& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BallReplacement& default_instance();

  void Swap(BallReplacement* other);

  // implements Message ----------------------------------------------

  inline BallReplacement* New() const { return New(NULL); }

  BallReplacement* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BallReplacement& from);
  void MergeFrom(const BallReplacement& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BallReplacement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double vx = 3;
  void clear_vx();
  static const int kVxFieldNumber = 3;
  double vx() const;
  void set_vx(double value);

  // optional double vy = 4;
  void clear_vy();
  static const int kVyFieldNumber = 4;
  double vy() const;
  void set_vy(double value);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.BallReplacement)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double vx_;
  double vy_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_replacement_2eproto();
  friend void protobuf_AssignDesc_replacement_2eproto();
  friend void protobuf_ShutdownFile_replacement_2eproto();

  void InitAsDefaultInstance();
  static BallReplacement* default_instance_;
};
// -------------------------------------------------------------------

class Replacement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Replacement) */ {
 public:
  Replacement();
  virtual ~Replacement();

  Replacement(const Replacement& from);

  inline Replacement& operator=(const Replacement& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Replacement& default_instance();

  void Swap(Replacement* other);

  // implements Message ----------------------------------------------

  inline Replacement* New() const { return New(NULL); }

  Replacement* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Replacement& from);
  void MergeFrom(const Replacement& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Replacement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fira_message.sim_to_ref.BallReplacement ball = 1;
  bool has_ball() const;
  void clear_ball();
  static const int kBallFieldNumber = 1;
  const ::fira_message::sim_to_ref::BallReplacement& ball() const;
  ::fira_message::sim_to_ref::BallReplacement* mutable_ball();
  ::fira_message::sim_to_ref::BallReplacement* release_ball();
  void set_allocated_ball(::fira_message::sim_to_ref::BallReplacement* ball);

  // repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
  int robots_size() const;
  void clear_robots();
  static const int kRobotsFieldNumber = 2;
  const ::fira_message::sim_to_ref::RobotReplacement& robots(int index) const;
  ::fira_message::sim_to_ref::RobotReplacement* mutable_robots(int index);
  ::fira_message::sim_to_ref::RobotReplacement* add_robots();
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >*
      mutable_robots();
  const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >&
      robots() const;

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Replacement)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::fira_message::sim_to_ref::BallReplacement* ball_;
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement > robots_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_replacement_2eproto();
  friend void protobuf_AssignDesc_replacement_2eproto();
  friend void protobuf_ShutdownFile_replacement_2eproto();

  void InitAsDefaultInstance();
  static Replacement* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RobotReplacement

// optional .fira_message.Robot position = 1;
inline bool RobotReplacement::has_position() const {
  return !_is_default_instance_ && position_ != NULL;
}
inline void RobotReplacement::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) delete position_;
  position_ = NULL;
}
inline const ::fira_message::Robot& RobotReplacement::position() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.position)
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::fira_message::Robot* RobotReplacement::mutable_position() {
  
  if (position_ == NULL) {
    position_ = new ::fira_message::Robot;
  }
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.RobotReplacement.position)
  return position_;
}
inline ::fira_message::Robot* RobotReplacement::release_position() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.RobotReplacement.position)
  
  ::fira_message::Robot* temp = position_;
  position_ = NULL;
  return temp;
}
inline void RobotReplacement::set_allocated_position(::fira_message::Robot* position) {
  delete position_;
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.RobotReplacement.position)
}

// optional bool yellowteam = 5;
inline void RobotReplacement::clear_yellowteam() {
  yellowteam_ = false;
}
inline bool RobotReplacement::yellowteam() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.yellowteam)
  return yellowteam_;
}
inline void RobotReplacement::set_yellowteam(bool value) {
  
  yellowteam_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.RobotReplacement.yellowteam)
}

// optional bool turnon = 6;
inline void RobotReplacement::clear_turnon() {
  turnon_ = false;
}
inline bool RobotReplacement::turnon() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.turnon)
  return turnon_;
}
inline void RobotReplacement::set_turnon(bool value) {
  
  turnon_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.RobotReplacement.turnon)
}

// -------------------------------------------------------------------

// BallReplacement

// optional double x = 1;
inline void BallReplacement::clear_x() {
  x_ = 0;
}
inline double BallReplacement::x() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.x)
  return x_;
}
inline void BallReplacement::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.x)
}

// optional double y = 2;
inline void BallReplacement::clear_y() {
  y_ = 0;
}
inline double BallReplacement::y() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.y)
  return y_;
}
inline void BallReplacement::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.y)
}

// optional double vx = 3;
inline void BallReplacement::clear_vx() {
  vx_ = 0;
}
inline double BallReplacement::vx() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.vx)
  return vx_;
}
inline void BallReplacement::set_vx(double value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.vx)
}

// optional double vy = 4;
inline void BallReplacement::clear_vy() {
  vy_ = 0;
}
inline double BallReplacement::vy() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.vy)
  return vy_;
}
inline void BallReplacement::set_vy(double value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.vy)
}

// -------------------------------------------------------------------

// Replacement

// optional .fira_message.sim_to_ref.BallReplacement ball = 1;
inline bool Replacement::has_ball() const {
  return !_is_default_instance_ && ball_ != NULL;
}
inline void Replacement::clear_ball() {
  if (GetArenaNoVirtual() == NULL && ball_ != NULL) delete ball_;
  ball_ = NULL;
}
inline const ::fira_message::sim_to_ref::BallReplacement& Replacement::ball() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Replacement.ball)
  return ball_ != NULL ? *ball_ : *default_instance_->ball_;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::mutable_ball() {
  
  if (ball_ == NULL) {
    ball_ = new ::fira_message::sim_to_ref::BallReplacement;
  }
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Replacement.ball)
  return ball_;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::release_ball() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.Replacement.ball)
  
  ::fira_message::sim_to_ref::BallReplacement* temp = ball_;
  ball_ = NULL;
  return temp;
}
inline void Replacement::set_allocated_ball(::fira_message::sim_to_ref::BallReplacement* ball) {
  delete ball_;
  ball_ = ball;
  if (ball) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.Replacement.ball)
}

// repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
inline int Replacement::robots_size() const {
  return robots_.size();
}
inline void Replacement::clear_robots() {
  robots_.Clear();
}
inline const ::fira_message::sim_to_ref::RobotReplacement& Replacement::robots(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Replacement.robots)
  return robots_.Get(index);
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::mutable_robots(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Replacement.robots)
  return robots_.Mutable(index);
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::add_robots() {
  // @@protoc_insertion_point(field_add:fira_message.sim_to_ref.Replacement.robots)
  return robots_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >*
Replacement::mutable_robots() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.sim_to_ref.Replacement.robots)
  return &robots_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >&
Replacement::robots() const {
  // @@protoc_insertion_point(field_list:fira_message.sim_to_ref.Replacement.robots)
  return robots_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_to_ref
}  // namespace fira_message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_replacement_2eproto__INCLUDED
