// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vssref_command.proto

#ifndef PROTOBUF_vssref_5fcommand_2eproto__INCLUDED
#define PROTOBUF_vssref_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "vssref_common.pb.h"
// @@protoc_insertion_point(includes)

namespace VSSRef {
namespace ref_to_team {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_vssref_5fcommand_2eproto();
void protobuf_AssignDesc_vssref_5fcommand_2eproto();
void protobuf_ShutdownFile_vssref_5fcommand_2eproto();

class VSSRef_Command;

// ===================================================================

class VSSRef_Command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:VSSRef.ref_to_team.VSSRef_Command) */ {
 public:
  VSSRef_Command();
  virtual ~VSSRef_Command();

  VSSRef_Command(const VSSRef_Command& from);

  inline VSSRef_Command& operator=(const VSSRef_Command& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VSSRef_Command& default_instance();

  void Swap(VSSRef_Command* other);

  // implements Message ----------------------------------------------

  inline VSSRef_Command* New() const { return New(NULL); }

  VSSRef_Command* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VSSRef_Command& from);
  void MergeFrom(const VSSRef_Command& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VSSRef_Command* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .VSSRef.Foul foul = 1;
  void clear_foul();
  static const int kFoulFieldNumber = 1;
  ::VSSRef::Foul foul() const;
  void set_foul(::VSSRef::Foul value);

  // optional .VSSRef.Color teamcolor = 2;
  void clear_teamcolor();
  static const int kTeamcolorFieldNumber = 2;
  ::VSSRef::Color teamcolor() const;
  void set_teamcolor(::VSSRef::Color value);

  // optional .VSSRef.Quadrant foulQuadrant = 3;
  void clear_foulquadrant();
  static const int kFoulQuadrantFieldNumber = 3;
  ::VSSRef::Quadrant foulquadrant() const;
  void set_foulquadrant(::VSSRef::Quadrant value);

  // optional double timestamp = 4;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 4;
  double timestamp() const;
  void set_timestamp(double value);

  // @@protoc_insertion_point(class_scope:VSSRef.ref_to_team.VSSRef_Command)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int foul_;
  int teamcolor_;
  double timestamp_;
  int foulquadrant_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_vssref_5fcommand_2eproto();
  friend void protobuf_AssignDesc_vssref_5fcommand_2eproto();
  friend void protobuf_ShutdownFile_vssref_5fcommand_2eproto();

  void InitAsDefaultInstance();
  static VSSRef_Command* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// VSSRef_Command

// optional .VSSRef.Foul foul = 1;
inline void VSSRef_Command::clear_foul() {
  foul_ = 0;
}
inline ::VSSRef::Foul VSSRef_Command::foul() const {
  // @@protoc_insertion_point(field_get:VSSRef.ref_to_team.VSSRef_Command.foul)
  return static_cast< ::VSSRef::Foul >(foul_);
}
inline void VSSRef_Command::set_foul(::VSSRef::Foul value) {
  
  foul_ = value;
  // @@protoc_insertion_point(field_set:VSSRef.ref_to_team.VSSRef_Command.foul)
}

// optional .VSSRef.Color teamcolor = 2;
inline void VSSRef_Command::clear_teamcolor() {
  teamcolor_ = 0;
}
inline ::VSSRef::Color VSSRef_Command::teamcolor() const {
  // @@protoc_insertion_point(field_get:VSSRef.ref_to_team.VSSRef_Command.teamcolor)
  return static_cast< ::VSSRef::Color >(teamcolor_);
}
inline void VSSRef_Command::set_teamcolor(::VSSRef::Color value) {
  
  teamcolor_ = value;
  // @@protoc_insertion_point(field_set:VSSRef.ref_to_team.VSSRef_Command.teamcolor)
}

// optional .VSSRef.Quadrant foulQuadrant = 3;
inline void VSSRef_Command::clear_foulquadrant() {
  foulquadrant_ = 0;
}
inline ::VSSRef::Quadrant VSSRef_Command::foulquadrant() const {
  // @@protoc_insertion_point(field_get:VSSRef.ref_to_team.VSSRef_Command.foulQuadrant)
  return static_cast< ::VSSRef::Quadrant >(foulquadrant_);
}
inline void VSSRef_Command::set_foulquadrant(::VSSRef::Quadrant value) {
  
  foulquadrant_ = value;
  // @@protoc_insertion_point(field_set:VSSRef.ref_to_team.VSSRef_Command.foulQuadrant)
}

// optional double timestamp = 4;
inline void VSSRef_Command::clear_timestamp() {
  timestamp_ = 0;
}
inline double VSSRef_Command::timestamp() const {
  // @@protoc_insertion_point(field_get:VSSRef.ref_to_team.VSSRef_Command.timestamp)
  return timestamp_;
}
inline void VSSRef_Command::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:VSSRef.ref_to_team.VSSRef_Command.timestamp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ref_to_team
}  // namespace VSSRef

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vssref_5fcommand_2eproto__INCLUDED
