// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace fira_message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class Ball;
class Field;
class Frame;
class Robot;

// ===================================================================

class Ball : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.Ball) */ {
 public:
  Ball();
  virtual ~Ball();

  Ball(const Ball& from);

  inline Ball& operator=(const Ball& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ball& default_instance();

  void Swap(Ball* other);

  // implements Message ----------------------------------------------

  inline Ball* New() const { return New(NULL); }

  Ball* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Ball& from);
  void MergeFrom(const Ball& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Ball* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // optional double vx = 4;
  void clear_vx();
  static const int kVxFieldNumber = 4;
  double vx() const;
  void set_vx(double value);

  // optional double vy = 5;
  void clear_vy();
  static const int kVyFieldNumber = 5;
  double vy() const;
  void set_vy(double value);

  // optional double vz = 6;
  void clear_vz();
  static const int kVzFieldNumber = 6;
  double vz() const;
  void set_vz(double value);

  // @@protoc_insertion_point(class_scope:fira_message.Ball)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double z_;
  double vx_;
  double vy_;
  double vz_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Ball* default_instance_;
};
// -------------------------------------------------------------------

class Robot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.Robot) */ {
 public:
  Robot();
  virtual ~Robot();

  Robot(const Robot& from);

  inline Robot& operator=(const Robot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Robot& default_instance();

  void Swap(Robot* other);

  // implements Message ----------------------------------------------

  inline Robot* New() const { return New(NULL); }

  Robot* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Robot& from);
  void MergeFrom(const Robot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Robot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 robot_id = 1;
  void clear_robot_id();
  static const int kRobotIdFieldNumber = 1;
  ::google::protobuf::uint32 robot_id() const;
  void set_robot_id(::google::protobuf::uint32 value);

  // optional double x = 2;
  void clear_x();
  static const int kXFieldNumber = 2;
  double x() const;
  void set_x(double value);

  // optional double y = 3;
  void clear_y();
  static const int kYFieldNumber = 3;
  double y() const;
  void set_y(double value);

  // optional double orientation = 4;
  void clear_orientation();
  static const int kOrientationFieldNumber = 4;
  double orientation() const;
  void set_orientation(double value);

  // optional double vx = 5;
  void clear_vx();
  static const int kVxFieldNumber = 5;
  double vx() const;
  void set_vx(double value);

  // optional double vy = 6;
  void clear_vy();
  static const int kVyFieldNumber = 6;
  double vy() const;
  void set_vy(double value);

  // optional double vorientation = 7;
  void clear_vorientation();
  static const int kVorientationFieldNumber = 7;
  double vorientation() const;
  void set_vorientation(double value);

  // @@protoc_insertion_point(class_scope:fira_message.Robot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double orientation_;
  double vx_;
  double vy_;
  double vorientation_;
  ::google::protobuf::uint32 robot_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Robot* default_instance_;
};
// -------------------------------------------------------------------

class Field : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.Field) */ {
 public:
  Field();
  virtual ~Field();

  Field(const Field& from);

  inline Field& operator=(const Field& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Field& default_instance();

  void Swap(Field* other);

  // implements Message ----------------------------------------------

  inline Field* New() const { return New(NULL); }

  Field* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Field& from);
  void MergeFrom(const Field& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Field* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double width = 1;
  void clear_width();
  static const int kWidthFieldNumber = 1;
  double width() const;
  void set_width(double value);

  // optional double length = 2;
  void clear_length();
  static const int kLengthFieldNumber = 2;
  double length() const;
  void set_length(double value);

  // optional double goal_width = 3;
  void clear_goal_width();
  static const int kGoalWidthFieldNumber = 3;
  double goal_width() const;
  void set_goal_width(double value);

  // optional double goal_depth = 4;
  void clear_goal_depth();
  static const int kGoalDepthFieldNumber = 4;
  double goal_depth() const;
  void set_goal_depth(double value);

  // @@protoc_insertion_point(class_scope:fira_message.Field)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double width_;
  double length_;
  double goal_width_;
  double goal_depth_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Field* default_instance_;
};
// -------------------------------------------------------------------

class Frame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.Frame) */ {
 public:
  Frame();
  virtual ~Frame();

  Frame(const Frame& from);

  inline Frame& operator=(const Frame& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Frame& default_instance();

  void Swap(Frame* other);

  // implements Message ----------------------------------------------

  inline Frame* New() const { return New(NULL); }

  Frame* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Frame& from);
  void MergeFrom(const Frame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Frame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fira_message.Ball ball = 1;
  bool has_ball() const;
  void clear_ball();
  static const int kBallFieldNumber = 1;
  const ::fira_message::Ball& ball() const;
  ::fira_message::Ball* mutable_ball();
  ::fira_message::Ball* release_ball();
  void set_allocated_ball(::fira_message::Ball* ball);

  // repeated .fira_message.Robot robots_yellow = 2;
  int robots_yellow_size() const;
  void clear_robots_yellow();
  static const int kRobotsYellowFieldNumber = 2;
  const ::fira_message::Robot& robots_yellow(int index) const;
  ::fira_message::Robot* mutable_robots_yellow(int index);
  ::fira_message::Robot* add_robots_yellow();
  ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >*
      mutable_robots_yellow();
  const ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >&
      robots_yellow() const;

  // repeated .fira_message.Robot robots_blue = 3;
  int robots_blue_size() const;
  void clear_robots_blue();
  static const int kRobotsBlueFieldNumber = 3;
  const ::fira_message::Robot& robots_blue(int index) const;
  ::fira_message::Robot* mutable_robots_blue(int index);
  ::fira_message::Robot* add_robots_blue();
  ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >*
      mutable_robots_blue();
  const ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >&
      robots_blue() const;

  // @@protoc_insertion_point(class_scope:fira_message.Frame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::fira_message::Ball* ball_;
  ::google::protobuf::RepeatedPtrField< ::fira_message::Robot > robots_yellow_;
  ::google::protobuf::RepeatedPtrField< ::fira_message::Robot > robots_blue_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Frame* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Ball

// optional double x = 1;
inline void Ball::clear_x() {
  x_ = 0;
}
inline double Ball::x() const {
  // @@protoc_insertion_point(field_get:fira_message.Ball.x)
  return x_;
}
inline void Ball::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Ball.x)
}

// optional double y = 2;
inline void Ball::clear_y() {
  y_ = 0;
}
inline double Ball::y() const {
  // @@protoc_insertion_point(field_get:fira_message.Ball.y)
  return y_;
}
inline void Ball::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Ball.y)
}

// optional double z = 3;
inline void Ball::clear_z() {
  z_ = 0;
}
inline double Ball::z() const {
  // @@protoc_insertion_point(field_get:fira_message.Ball.z)
  return z_;
}
inline void Ball::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Ball.z)
}

// optional double vx = 4;
inline void Ball::clear_vx() {
  vx_ = 0;
}
inline double Ball::vx() const {
  // @@protoc_insertion_point(field_get:fira_message.Ball.vx)
  return vx_;
}
inline void Ball::set_vx(double value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Ball.vx)
}

// optional double vy = 5;
inline void Ball::clear_vy() {
  vy_ = 0;
}
inline double Ball::vy() const {
  // @@protoc_insertion_point(field_get:fira_message.Ball.vy)
  return vy_;
}
inline void Ball::set_vy(double value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Ball.vy)
}

// optional double vz = 6;
inline void Ball::clear_vz() {
  vz_ = 0;
}
inline double Ball::vz() const {
  // @@protoc_insertion_point(field_get:fira_message.Ball.vz)
  return vz_;
}
inline void Ball::set_vz(double value) {
  
  vz_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Ball.vz)
}

// -------------------------------------------------------------------

// Robot

// optional uint32 robot_id = 1;
inline void Robot::clear_robot_id() {
  robot_id_ = 0u;
}
inline ::google::protobuf::uint32 Robot::robot_id() const {
  // @@protoc_insertion_point(field_get:fira_message.Robot.robot_id)
  return robot_id_;
}
inline void Robot::set_robot_id(::google::protobuf::uint32 value) {
  
  robot_id_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Robot.robot_id)
}

// optional double x = 2;
inline void Robot::clear_x() {
  x_ = 0;
}
inline double Robot::x() const {
  // @@protoc_insertion_point(field_get:fira_message.Robot.x)
  return x_;
}
inline void Robot::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Robot.x)
}

// optional double y = 3;
inline void Robot::clear_y() {
  y_ = 0;
}
inline double Robot::y() const {
  // @@protoc_insertion_point(field_get:fira_message.Robot.y)
  return y_;
}
inline void Robot::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Robot.y)
}

// optional double orientation = 4;
inline void Robot::clear_orientation() {
  orientation_ = 0;
}
inline double Robot::orientation() const {
  // @@protoc_insertion_point(field_get:fira_message.Robot.orientation)
  return orientation_;
}
inline void Robot::set_orientation(double value) {
  
  orientation_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Robot.orientation)
}

// optional double vx = 5;
inline void Robot::clear_vx() {
  vx_ = 0;
}
inline double Robot::vx() const {
  // @@protoc_insertion_point(field_get:fira_message.Robot.vx)
  return vx_;
}
inline void Robot::set_vx(double value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Robot.vx)
}

// optional double vy = 6;
inline void Robot::clear_vy() {
  vy_ = 0;
}
inline double Robot::vy() const {
  // @@protoc_insertion_point(field_get:fira_message.Robot.vy)
  return vy_;
}
inline void Robot::set_vy(double value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Robot.vy)
}

// optional double vorientation = 7;
inline void Robot::clear_vorientation() {
  vorientation_ = 0;
}
inline double Robot::vorientation() const {
  // @@protoc_insertion_point(field_get:fira_message.Robot.vorientation)
  return vorientation_;
}
inline void Robot::set_vorientation(double value) {
  
  vorientation_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Robot.vorientation)
}

// -------------------------------------------------------------------

// Field

// optional double width = 1;
inline void Field::clear_width() {
  width_ = 0;
}
inline double Field::width() const {
  // @@protoc_insertion_point(field_get:fira_message.Field.width)
  return width_;
}
inline void Field::set_width(double value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Field.width)
}

// optional double length = 2;
inline void Field::clear_length() {
  length_ = 0;
}
inline double Field::length() const {
  // @@protoc_insertion_point(field_get:fira_message.Field.length)
  return length_;
}
inline void Field::set_length(double value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Field.length)
}

// optional double goal_width = 3;
inline void Field::clear_goal_width() {
  goal_width_ = 0;
}
inline double Field::goal_width() const {
  // @@protoc_insertion_point(field_get:fira_message.Field.goal_width)
  return goal_width_;
}
inline void Field::set_goal_width(double value) {
  
  goal_width_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Field.goal_width)
}

// optional double goal_depth = 4;
inline void Field::clear_goal_depth() {
  goal_depth_ = 0;
}
inline double Field::goal_depth() const {
  // @@protoc_insertion_point(field_get:fira_message.Field.goal_depth)
  return goal_depth_;
}
inline void Field::set_goal_depth(double value) {
  
  goal_depth_ = value;
  // @@protoc_insertion_point(field_set:fira_message.Field.goal_depth)
}

// -------------------------------------------------------------------

// Frame

// optional .fira_message.Ball ball = 1;
inline bool Frame::has_ball() const {
  return !_is_default_instance_ && ball_ != NULL;
}
inline void Frame::clear_ball() {
  if (GetArenaNoVirtual() == NULL && ball_ != NULL) delete ball_;
  ball_ = NULL;
}
inline const ::fira_message::Ball& Frame::ball() const {
  // @@protoc_insertion_point(field_get:fira_message.Frame.ball)
  return ball_ != NULL ? *ball_ : *default_instance_->ball_;
}
inline ::fira_message::Ball* Frame::mutable_ball() {
  
  if (ball_ == NULL) {
    ball_ = new ::fira_message::Ball;
  }
  // @@protoc_insertion_point(field_mutable:fira_message.Frame.ball)
  return ball_;
}
inline ::fira_message::Ball* Frame::release_ball() {
  // @@protoc_insertion_point(field_release:fira_message.Frame.ball)
  
  ::fira_message::Ball* temp = ball_;
  ball_ = NULL;
  return temp;
}
inline void Frame::set_allocated_ball(::fira_message::Ball* ball) {
  delete ball_;
  ball_ = ball;
  if (ball) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:fira_message.Frame.ball)
}

// repeated .fira_message.Robot robots_yellow = 2;
inline int Frame::robots_yellow_size() const {
  return robots_yellow_.size();
}
inline void Frame::clear_robots_yellow() {
  robots_yellow_.Clear();
}
inline const ::fira_message::Robot& Frame::robots_yellow(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.Frame.robots_yellow)
  return robots_yellow_.Get(index);
}
inline ::fira_message::Robot* Frame::mutable_robots_yellow(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.Frame.robots_yellow)
  return robots_yellow_.Mutable(index);
}
inline ::fira_message::Robot* Frame::add_robots_yellow() {
  // @@protoc_insertion_point(field_add:fira_message.Frame.robots_yellow)
  return robots_yellow_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >*
Frame::mutable_robots_yellow() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.Frame.robots_yellow)
  return &robots_yellow_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >&
Frame::robots_yellow() const {
  // @@protoc_insertion_point(field_list:fira_message.Frame.robots_yellow)
  return robots_yellow_;
}

// repeated .fira_message.Robot robots_blue = 3;
inline int Frame::robots_blue_size() const {
  return robots_blue_.size();
}
inline void Frame::clear_robots_blue() {
  robots_blue_.Clear();
}
inline const ::fira_message::Robot& Frame::robots_blue(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.Frame.robots_blue)
  return robots_blue_.Get(index);
}
inline ::fira_message::Robot* Frame::mutable_robots_blue(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.Frame.robots_blue)
  return robots_blue_.Mutable(index);
}
inline ::fira_message::Robot* Frame::add_robots_blue() {
  // @@protoc_insertion_point(field_add:fira_message.Frame.robots_blue)
  return robots_blue_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >*
Frame::mutable_robots_blue() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.Frame.robots_blue)
  return &robots_blue_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fira_message::Robot >&
Frame::robots_blue() const {
  // @@protoc_insertion_point(field_list:fira_message.Frame.robots_blue)
  return robots_blue_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fira_message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
