// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace fira_message {
namespace sim_to_ref {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class Ball;
class Command;
class Commands;
class Environment;
class Field;
class Frame;
class Packet;
class Robot;

// ===================================================================

class Ball : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Ball) */ {
 public:
  Ball();
  virtual ~Ball();

  Ball(const Ball& from);

  inline Ball& operator=(const Ball& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ball& default_instance();

  void Swap(Ball* other);

  // implements Message ----------------------------------------------

  inline Ball* New() const { return New(NULL); }

  Ball* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Ball& from);
  void MergeFrom(const Ball& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Ball* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // optional double vx = 4;
  void clear_vx();
  static const int kVxFieldNumber = 4;
  double vx() const;
  void set_vx(double value);

  // optional double vy = 5;
  void clear_vy();
  static const int kVyFieldNumber = 5;
  double vy() const;
  void set_vy(double value);

  // optional double vz = 6;
  void clear_vz();
  static const int kVzFieldNumber = 6;
  double vz() const;
  void set_vz(double value);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Ball)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double z_;
  double vx_;
  double vy_;
  double vz_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Ball* default_instance_;
};
// -------------------------------------------------------------------

class Robot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Robot) */ {
 public:
  Robot();
  virtual ~Robot();

  Robot(const Robot& from);

  inline Robot& operator=(const Robot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Robot& default_instance();

  void Swap(Robot* other);

  // implements Message ----------------------------------------------

  inline Robot* New() const { return New(NULL); }

  Robot* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Robot& from);
  void MergeFrom(const Robot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Robot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 robot_id = 1;
  void clear_robot_id();
  static const int kRobotIdFieldNumber = 1;
  ::google::protobuf::uint32 robot_id() const;
  void set_robot_id(::google::protobuf::uint32 value);

  // optional double x = 2;
  void clear_x();
  static const int kXFieldNumber = 2;
  double x() const;
  void set_x(double value);

  // optional double y = 3;
  void clear_y();
  static const int kYFieldNumber = 3;
  double y() const;
  void set_y(double value);

  // optional double orientation = 4;
  void clear_orientation();
  static const int kOrientationFieldNumber = 4;
  double orientation() const;
  void set_orientation(double value);

  // optional double vx = 5;
  void clear_vx();
  static const int kVxFieldNumber = 5;
  double vx() const;
  void set_vx(double value);

  // optional double vy = 6;
  void clear_vy();
  static const int kVyFieldNumber = 6;
  double vy() const;
  void set_vy(double value);

  // optional double vorientation = 7;
  void clear_vorientation();
  static const int kVorientationFieldNumber = 7;
  double vorientation() const;
  void set_vorientation(double value);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Robot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double orientation_;
  double vx_;
  double vy_;
  double vorientation_;
  ::google::protobuf::uint32 robot_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Robot* default_instance_;
};
// -------------------------------------------------------------------

class Field : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Field) */ {
 public:
  Field();
  virtual ~Field();

  Field(const Field& from);

  inline Field& operator=(const Field& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Field& default_instance();

  void Swap(Field* other);

  // implements Message ----------------------------------------------

  inline Field* New() const { return New(NULL); }

  Field* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Field& from);
  void MergeFrom(const Field& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Field* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double width = 1;
  void clear_width();
  static const int kWidthFieldNumber = 1;
  double width() const;
  void set_width(double value);

  // optional double length = 2;
  void clear_length();
  static const int kLengthFieldNumber = 2;
  double length() const;
  void set_length(double value);

  // optional double goal_width = 3;
  void clear_goal_width();
  static const int kGoalWidthFieldNumber = 3;
  double goal_width() const;
  void set_goal_width(double value);

  // optional double goal_depth = 4;
  void clear_goal_depth();
  static const int kGoalDepthFieldNumber = 4;
  double goal_depth() const;
  void set_goal_depth(double value);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Field)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double width_;
  double length_;
  double goal_width_;
  double goal_depth_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Field* default_instance_;
};
// -------------------------------------------------------------------

class Frame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Frame) */ {
 public:
  Frame();
  virtual ~Frame();

  Frame(const Frame& from);

  inline Frame& operator=(const Frame& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Frame& default_instance();

  void Swap(Frame* other);

  // implements Message ----------------------------------------------

  inline Frame* New() const { return New(NULL); }

  Frame* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Frame& from);
  void MergeFrom(const Frame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Frame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fira_message.sim_to_ref.Ball ball = 1;
  bool has_ball() const;
  void clear_ball();
  static const int kBallFieldNumber = 1;
  const ::fira_message::sim_to_ref::Ball& ball() const;
  ::fira_message::sim_to_ref::Ball* mutable_ball();
  ::fira_message::sim_to_ref::Ball* release_ball();
  void set_allocated_ball(::fira_message::sim_to_ref::Ball* ball);

  // repeated .fira_message.sim_to_ref.Robot robots_yellow = 2;
  int robots_yellow_size() const;
  void clear_robots_yellow();
  static const int kRobotsYellowFieldNumber = 2;
  const ::fira_message::sim_to_ref::Robot& robots_yellow(int index) const;
  ::fira_message::sim_to_ref::Robot* mutable_robots_yellow(int index);
  ::fira_message::sim_to_ref::Robot* add_robots_yellow();
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >*
      mutable_robots_yellow();
  const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >&
      robots_yellow() const;

  // repeated .fira_message.sim_to_ref.Robot robots_blue = 3;
  int robots_blue_size() const;
  void clear_robots_blue();
  static const int kRobotsBlueFieldNumber = 3;
  const ::fira_message::sim_to_ref::Robot& robots_blue(int index) const;
  ::fira_message::sim_to_ref::Robot* mutable_robots_blue(int index);
  ::fira_message::sim_to_ref::Robot* add_robots_blue();
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >*
      mutable_robots_blue();
  const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >&
      robots_blue() const;

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Frame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::fira_message::sim_to_ref::Ball* ball_;
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot > robots_yellow_;
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot > robots_blue_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Frame* default_instance_;
};
// -------------------------------------------------------------------

class Command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Command) */ {
 public:
  Command();
  virtual ~Command();

  Command(const Command& from);

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Command& default_instance();

  void Swap(Command* other);

  // implements Message ----------------------------------------------

  inline Command* New() const { return New(NULL); }

  Command* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Command& from);
  void MergeFrom(const Command& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Command* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional bool yellowteam = 2;
  void clear_yellowteam();
  static const int kYellowteamFieldNumber = 2;
  bool yellowteam() const;
  void set_yellowteam(bool value);

  // optional double wheel_left = 6;
  void clear_wheel_left();
  static const int kWheelLeftFieldNumber = 6;
  double wheel_left() const;
  void set_wheel_left(double value);

  // optional double wheel_right = 7;
  void clear_wheel_right();
  static const int kWheelRightFieldNumber = 7;
  double wheel_right() const;
  void set_wheel_right(double value);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Command)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 id_;
  bool yellowteam_;
  double wheel_left_;
  double wheel_right_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Command* default_instance_;
};
// -------------------------------------------------------------------

class Commands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Commands) */ {
 public:
  Commands();
  virtual ~Commands();

  Commands(const Commands& from);

  inline Commands& operator=(const Commands& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Commands& default_instance();

  void Swap(Commands* other);

  // implements Message ----------------------------------------------

  inline Commands* New() const { return New(NULL); }

  Commands* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Commands& from);
  void MergeFrom(const Commands& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Commands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .fira_message.sim_to_ref.Command robot_commands = 1;
  int robot_commands_size() const;
  void clear_robot_commands();
  static const int kRobotCommandsFieldNumber = 1;
  const ::fira_message::sim_to_ref::Command& robot_commands(int index) const;
  ::fira_message::sim_to_ref::Command* mutable_robot_commands(int index);
  ::fira_message::sim_to_ref::Command* add_robot_commands();
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Command >*
      mutable_robot_commands();
  const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Command >&
      robot_commands() const;

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Commands)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Command > robot_commands_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Commands* default_instance_;
};
// -------------------------------------------------------------------

class Packet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Packet) */ {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  void Swap(Packet* other);

  // implements Message ----------------------------------------------

  inline Packet* New() const { return New(NULL); }

  Packet* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Packet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fira_message.sim_to_ref.Commands cmd = 1;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 1;
  const ::fira_message::sim_to_ref::Commands& cmd() const;
  ::fira_message::sim_to_ref::Commands* mutable_cmd();
  ::fira_message::sim_to_ref::Commands* release_cmd();
  void set_allocated_cmd(::fira_message::sim_to_ref::Commands* cmd);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Packet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::fira_message::sim_to_ref::Commands* cmd_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Packet* default_instance_;
};
// -------------------------------------------------------------------

class Environment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Environment) */ {
 public:
  Environment();
  virtual ~Environment();

  Environment(const Environment& from);

  inline Environment& operator=(const Environment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Environment& default_instance();

  void Swap(Environment* other);

  // implements Message ----------------------------------------------

  inline Environment* New() const { return New(NULL); }

  Environment* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Environment& from);
  void MergeFrom(const Environment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Environment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 step = 1;
  void clear_step();
  static const int kStepFieldNumber = 1;
  ::google::protobuf::uint32 step() const;
  void set_step(::google::protobuf::uint32 value);

  // optional .fira_message.sim_to_ref.Frame frame = 2;
  bool has_frame() const;
  void clear_frame();
  static const int kFrameFieldNumber = 2;
  const ::fira_message::sim_to_ref::Frame& frame() const;
  ::fira_message::sim_to_ref::Frame* mutable_frame();
  ::fira_message::sim_to_ref::Frame* release_frame();
  void set_allocated_frame(::fira_message::sim_to_ref::Frame* frame);

  // optional .fira_message.sim_to_ref.Field field = 3;
  bool has_field() const;
  void clear_field();
  static const int kFieldFieldNumber = 3;
  const ::fira_message::sim_to_ref::Field& field() const;
  ::fira_message::sim_to_ref::Field* mutable_field();
  ::fira_message::sim_to_ref::Field* release_field();
  void set_allocated_field(::fira_message::sim_to_ref::Field* field);

  // optional uint32 goals_blue = 4;
  void clear_goals_blue();
  static const int kGoalsBlueFieldNumber = 4;
  ::google::protobuf::uint32 goals_blue() const;
  void set_goals_blue(::google::protobuf::uint32 value);

  // optional uint32 goals_yellow = 5;
  void clear_goals_yellow();
  static const int kGoalsYellowFieldNumber = 5;
  ::google::protobuf::uint32 goals_yellow() const;
  void set_goals_yellow(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Environment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::fira_message::sim_to_ref::Frame* frame_;
  ::google::protobuf::uint32 step_;
  ::google::protobuf::uint32 goals_blue_;
  ::fira_message::sim_to_ref::Field* field_;
  ::google::protobuf::uint32 goals_yellow_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static Environment* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Ball

// optional double x = 1;
inline void Ball::clear_x() {
  x_ = 0;
}
inline double Ball::x() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Ball.x)
  return x_;
}
inline void Ball::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Ball.x)
}

// optional double y = 2;
inline void Ball::clear_y() {
  y_ = 0;
}
inline double Ball::y() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Ball.y)
  return y_;
}
inline void Ball::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Ball.y)
}

// optional double z = 3;
inline void Ball::clear_z() {
  z_ = 0;
}
inline double Ball::z() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Ball.z)
  return z_;
}
inline void Ball::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Ball.z)
}

// optional double vx = 4;
inline void Ball::clear_vx() {
  vx_ = 0;
}
inline double Ball::vx() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Ball.vx)
  return vx_;
}
inline void Ball::set_vx(double value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Ball.vx)
}

// optional double vy = 5;
inline void Ball::clear_vy() {
  vy_ = 0;
}
inline double Ball::vy() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Ball.vy)
  return vy_;
}
inline void Ball::set_vy(double value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Ball.vy)
}

// optional double vz = 6;
inline void Ball::clear_vz() {
  vz_ = 0;
}
inline double Ball::vz() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Ball.vz)
  return vz_;
}
inline void Ball::set_vz(double value) {
  
  vz_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Ball.vz)
}

// -------------------------------------------------------------------

// Robot

// optional uint32 robot_id = 1;
inline void Robot::clear_robot_id() {
  robot_id_ = 0u;
}
inline ::google::protobuf::uint32 Robot::robot_id() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Robot.robot_id)
  return robot_id_;
}
inline void Robot::set_robot_id(::google::protobuf::uint32 value) {
  
  robot_id_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Robot.robot_id)
}

// optional double x = 2;
inline void Robot::clear_x() {
  x_ = 0;
}
inline double Robot::x() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Robot.x)
  return x_;
}
inline void Robot::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Robot.x)
}

// optional double y = 3;
inline void Robot::clear_y() {
  y_ = 0;
}
inline double Robot::y() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Robot.y)
  return y_;
}
inline void Robot::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Robot.y)
}

// optional double orientation = 4;
inline void Robot::clear_orientation() {
  orientation_ = 0;
}
inline double Robot::orientation() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Robot.orientation)
  return orientation_;
}
inline void Robot::set_orientation(double value) {
  
  orientation_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Robot.orientation)
}

// optional double vx = 5;
inline void Robot::clear_vx() {
  vx_ = 0;
}
inline double Robot::vx() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Robot.vx)
  return vx_;
}
inline void Robot::set_vx(double value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Robot.vx)
}

// optional double vy = 6;
inline void Robot::clear_vy() {
  vy_ = 0;
}
inline double Robot::vy() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Robot.vy)
  return vy_;
}
inline void Robot::set_vy(double value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Robot.vy)
}

// optional double vorientation = 7;
inline void Robot::clear_vorientation() {
  vorientation_ = 0;
}
inline double Robot::vorientation() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Robot.vorientation)
  return vorientation_;
}
inline void Robot::set_vorientation(double value) {
  
  vorientation_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Robot.vorientation)
}

// -------------------------------------------------------------------

// Field

// optional double width = 1;
inline void Field::clear_width() {
  width_ = 0;
}
inline double Field::width() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Field.width)
  return width_;
}
inline void Field::set_width(double value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Field.width)
}

// optional double length = 2;
inline void Field::clear_length() {
  length_ = 0;
}
inline double Field::length() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Field.length)
  return length_;
}
inline void Field::set_length(double value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Field.length)
}

// optional double goal_width = 3;
inline void Field::clear_goal_width() {
  goal_width_ = 0;
}
inline double Field::goal_width() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Field.goal_width)
  return goal_width_;
}
inline void Field::set_goal_width(double value) {
  
  goal_width_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Field.goal_width)
}

// optional double goal_depth = 4;
inline void Field::clear_goal_depth() {
  goal_depth_ = 0;
}
inline double Field::goal_depth() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Field.goal_depth)
  return goal_depth_;
}
inline void Field::set_goal_depth(double value) {
  
  goal_depth_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Field.goal_depth)
}

// -------------------------------------------------------------------

// Frame

// optional .fira_message.sim_to_ref.Ball ball = 1;
inline bool Frame::has_ball() const {
  return !_is_default_instance_ && ball_ != NULL;
}
inline void Frame::clear_ball() {
  if (GetArenaNoVirtual() == NULL && ball_ != NULL) delete ball_;
  ball_ = NULL;
}
inline const ::fira_message::sim_to_ref::Ball& Frame::ball() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Frame.ball)
  return ball_ != NULL ? *ball_ : *default_instance_->ball_;
}
inline ::fira_message::sim_to_ref::Ball* Frame::mutable_ball() {
  
  if (ball_ == NULL) {
    ball_ = new ::fira_message::sim_to_ref::Ball;
  }
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Frame.ball)
  return ball_;
}
inline ::fira_message::sim_to_ref::Ball* Frame::release_ball() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.Frame.ball)
  
  ::fira_message::sim_to_ref::Ball* temp = ball_;
  ball_ = NULL;
  return temp;
}
inline void Frame::set_allocated_ball(::fira_message::sim_to_ref::Ball* ball) {
  delete ball_;
  ball_ = ball;
  if (ball) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.Frame.ball)
}

// repeated .fira_message.sim_to_ref.Robot robots_yellow = 2;
inline int Frame::robots_yellow_size() const {
  return robots_yellow_.size();
}
inline void Frame::clear_robots_yellow() {
  robots_yellow_.Clear();
}
inline const ::fira_message::sim_to_ref::Robot& Frame::robots_yellow(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Frame.robots_yellow)
  return robots_yellow_.Get(index);
}
inline ::fira_message::sim_to_ref::Robot* Frame::mutable_robots_yellow(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Frame.robots_yellow)
  return robots_yellow_.Mutable(index);
}
inline ::fira_message::sim_to_ref::Robot* Frame::add_robots_yellow() {
  // @@protoc_insertion_point(field_add:fira_message.sim_to_ref.Frame.robots_yellow)
  return robots_yellow_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >*
Frame::mutable_robots_yellow() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.sim_to_ref.Frame.robots_yellow)
  return &robots_yellow_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >&
Frame::robots_yellow() const {
  // @@protoc_insertion_point(field_list:fira_message.sim_to_ref.Frame.robots_yellow)
  return robots_yellow_;
}

// repeated .fira_message.sim_to_ref.Robot robots_blue = 3;
inline int Frame::robots_blue_size() const {
  return robots_blue_.size();
}
inline void Frame::clear_robots_blue() {
  robots_blue_.Clear();
}
inline const ::fira_message::sim_to_ref::Robot& Frame::robots_blue(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Frame.robots_blue)
  return robots_blue_.Get(index);
}
inline ::fira_message::sim_to_ref::Robot* Frame::mutable_robots_blue(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Frame.robots_blue)
  return robots_blue_.Mutable(index);
}
inline ::fira_message::sim_to_ref::Robot* Frame::add_robots_blue() {
  // @@protoc_insertion_point(field_add:fira_message.sim_to_ref.Frame.robots_blue)
  return robots_blue_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >*
Frame::mutable_robots_blue() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.sim_to_ref.Frame.robots_blue)
  return &robots_blue_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Robot >&
Frame::robots_blue() const {
  // @@protoc_insertion_point(field_list:fira_message.sim_to_ref.Frame.robots_blue)
  return robots_blue_;
}

// -------------------------------------------------------------------

// Command

// optional uint32 id = 1;
inline void Command::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 Command::id() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Command.id)
  return id_;
}
inline void Command::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Command.id)
}

// optional bool yellowteam = 2;
inline void Command::clear_yellowteam() {
  yellowteam_ = false;
}
inline bool Command::yellowteam() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Command.yellowteam)
  return yellowteam_;
}
inline void Command::set_yellowteam(bool value) {
  
  yellowteam_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Command.yellowteam)
}

// optional double wheel_left = 6;
inline void Command::clear_wheel_left() {
  wheel_left_ = 0;
}
inline double Command::wheel_left() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Command.wheel_left)
  return wheel_left_;
}
inline void Command::set_wheel_left(double value) {
  
  wheel_left_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Command.wheel_left)
}

// optional double wheel_right = 7;
inline void Command::clear_wheel_right() {
  wheel_right_ = 0;
}
inline double Command::wheel_right() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Command.wheel_right)
  return wheel_right_;
}
inline void Command::set_wheel_right(double value) {
  
  wheel_right_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Command.wheel_right)
}

// -------------------------------------------------------------------

// Commands

// repeated .fira_message.sim_to_ref.Command robot_commands = 1;
inline int Commands::robot_commands_size() const {
  return robot_commands_.size();
}
inline void Commands::clear_robot_commands() {
  robot_commands_.Clear();
}
inline const ::fira_message::sim_to_ref::Command& Commands::robot_commands(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Commands.robot_commands)
  return robot_commands_.Get(index);
}
inline ::fira_message::sim_to_ref::Command* Commands::mutable_robot_commands(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Commands.robot_commands)
  return robot_commands_.Mutable(index);
}
inline ::fira_message::sim_to_ref::Command* Commands::add_robot_commands() {
  // @@protoc_insertion_point(field_add:fira_message.sim_to_ref.Commands.robot_commands)
  return robot_commands_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Command >*
Commands::mutable_robot_commands() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.sim_to_ref.Commands.robot_commands)
  return &robot_commands_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fira_message::sim_to_ref::Command >&
Commands::robot_commands() const {
  // @@protoc_insertion_point(field_list:fira_message.sim_to_ref.Commands.robot_commands)
  return robot_commands_;
}

// -------------------------------------------------------------------

// Packet

// optional .fira_message.sim_to_ref.Commands cmd = 1;
inline bool Packet::has_cmd() const {
  return !_is_default_instance_ && cmd_ != NULL;
}
inline void Packet::clear_cmd() {
  if (GetArenaNoVirtual() == NULL && cmd_ != NULL) delete cmd_;
  cmd_ = NULL;
}
inline const ::fira_message::sim_to_ref::Commands& Packet::cmd() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Packet.cmd)
  return cmd_ != NULL ? *cmd_ : *default_instance_->cmd_;
}
inline ::fira_message::sim_to_ref::Commands* Packet::mutable_cmd() {
  
  if (cmd_ == NULL) {
    cmd_ = new ::fira_message::sim_to_ref::Commands;
  }
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Packet.cmd)
  return cmd_;
}
inline ::fira_message::sim_to_ref::Commands* Packet::release_cmd() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.Packet.cmd)
  
  ::fira_message::sim_to_ref::Commands* temp = cmd_;
  cmd_ = NULL;
  return temp;
}
inline void Packet::set_allocated_cmd(::fira_message::sim_to_ref::Commands* cmd) {
  delete cmd_;
  cmd_ = cmd;
  if (cmd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.Packet.cmd)
}

// -------------------------------------------------------------------

// Environment

// optional uint32 step = 1;
inline void Environment::clear_step() {
  step_ = 0u;
}
inline ::google::protobuf::uint32 Environment::step() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Environment.step)
  return step_;
}
inline void Environment::set_step(::google::protobuf::uint32 value) {
  
  step_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Environment.step)
}

// optional .fira_message.sim_to_ref.Frame frame = 2;
inline bool Environment::has_frame() const {
  return !_is_default_instance_ && frame_ != NULL;
}
inline void Environment::clear_frame() {
  if (GetArenaNoVirtual() == NULL && frame_ != NULL) delete frame_;
  frame_ = NULL;
}
inline const ::fira_message::sim_to_ref::Frame& Environment::frame() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Environment.frame)
  return frame_ != NULL ? *frame_ : *default_instance_->frame_;
}
inline ::fira_message::sim_to_ref::Frame* Environment::mutable_frame() {
  
  if (frame_ == NULL) {
    frame_ = new ::fira_message::sim_to_ref::Frame;
  }
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Environment.frame)
  return frame_;
}
inline ::fira_message::sim_to_ref::Frame* Environment::release_frame() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.Environment.frame)
  
  ::fira_message::sim_to_ref::Frame* temp = frame_;
  frame_ = NULL;
  return temp;
}
inline void Environment::set_allocated_frame(::fira_message::sim_to_ref::Frame* frame) {
  delete frame_;
  frame_ = frame;
  if (frame) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.Environment.frame)
}

// optional .fira_message.sim_to_ref.Field field = 3;
inline bool Environment::has_field() const {
  return !_is_default_instance_ && field_ != NULL;
}
inline void Environment::clear_field() {
  if (GetArenaNoVirtual() == NULL && field_ != NULL) delete field_;
  field_ = NULL;
}
inline const ::fira_message::sim_to_ref::Field& Environment::field() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Environment.field)
  return field_ != NULL ? *field_ : *default_instance_->field_;
}
inline ::fira_message::sim_to_ref::Field* Environment::mutable_field() {
  
  if (field_ == NULL) {
    field_ = new ::fira_message::sim_to_ref::Field;
  }
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Environment.field)
  return field_;
}
inline ::fira_message::sim_to_ref::Field* Environment::release_field() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.Environment.field)
  
  ::fira_message::sim_to_ref::Field* temp = field_;
  field_ = NULL;
  return temp;
}
inline void Environment::set_allocated_field(::fira_message::sim_to_ref::Field* field) {
  delete field_;
  field_ = field;
  if (field) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.Environment.field)
}

// optional uint32 goals_blue = 4;
inline void Environment::clear_goals_blue() {
  goals_blue_ = 0u;
}
inline ::google::protobuf::uint32 Environment::goals_blue() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Environment.goals_blue)
  return goals_blue_;
}
inline void Environment::set_goals_blue(::google::protobuf::uint32 value) {
  
  goals_blue_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Environment.goals_blue)
}

// optional uint32 goals_yellow = 5;
inline void Environment::clear_goals_yellow() {
  goals_yellow_ = 0u;
}
inline ::google::protobuf::uint32 Environment::goals_yellow() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Environment.goals_yellow)
  return goals_yellow_;
}
inline void Environment::set_goals_yellow(::google::protobuf::uint32 value) {
  
  goals_yellow_ = value;
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.Environment.goals_yellow)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_to_ref
}  // namespace fira_message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
